- name: Ensure directory for MongoDB Jumpbox
  file:
    path: "{{ global_defaults.app_base_path }}/mongo_jumpbox"
    state: directory
    mode: '0755'

- name: Copy docker-compose template for MongoDB Jumpbox
  template:
    src: docker-compose.yml.j2
    dest: "{{ global_defaults.app_base_path }}/mongo_jumpbox/docker-compose.yml"

- name: Deploy MongoDB Jumpbox container
  community.docker.docker_compose_v2:
    project_src: "{{ global_defaults.app_base_path }}/mongo_jumpbox"
    state: present
    recreate: always
    remove_orphans: true