- name: Ensure config and compose directory exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ global_defaults.puid }}"
    group: "{{ global_defaults.pgid }}"
    mode: '0755'
  loop:
    - "{{ global_defaults.homepage_config_path }}"
    - "{{ global_defaults.homepage_compose_path }}"
  tags: [homepage]

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ global_defaults.homepage_compose_path }}/docker-compose.yml"
  tags: [homepage]


- name: Template Homepage config files
  template:
    src: "{{ item.src }}"
    dest: "{{ global_defaults.homepage_config_path }}/{{ item.dest }}"
  loop:
    - { src: 'settings.yaml.j2', dest: 'settings.yaml' }
    - { src: 'services.yaml.j2', dest: 'services.yaml' }
    - { src: 'docker.yaml.j2',   dest: 'docker.yaml' }
    - { src: 'custom.css.j2',    dest: 'custom.css' }
  notify: restart homepage
  tags: [homepage]


- name: Run docker compose
  command: docker compose up -d
  args:
    chdir: "{{ global_defaults.homepage_compose_path }}"
  tags: [homepage]