---
#- name: Ensure docker-compose file exists
#  copy:
#    src: files/docker-compose.yaml
#    dest: "{{ global_defaults.app_base_path }}/docker-compose.yaml"
#    owner: dockeruser
#    group: dockeruser
#    mode: '0644'
- name: Generate .env file from template
  template:
    src: "templates/.env.j2"
    dest: "{{ global_defaults.app_base_path }}/.env"
    owner: dockeruser
    group: dockeruser
    mode: "0644"

- name: Generate docker-compose.yaml from template
  template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ global_defaults.app_base_path }}/docker-compose.yaml"
    owner: dockeruser
    group: dockeruser
    mode: "0644"
#    force: yes # Force changes in the template to the docker-compose.yaml

- name: Deploy Docker containers (Compose v2)
  community.docker.docker_compose_v2:
    project_src: "{{ global_defaults.app_base_path }}"
    files:
      - docker-compose.yaml
    state: present
    recreate: always
    remove_orphans: true
