---
#- name: Ensure docker-compose file exists
#  copy:
#    src: files/docker-compose.yaml
#    dest: "{{ global_defaults.app_base_path }}/docker-compose.yaml"
#    owner: dockeruser
#    group: dockeruser
#    mode: '0644'
- name: Generate .env file from template
  template:
    src: "templates/.env.j2"
    dest: "{{ global_defaults.app_base_path }}/.env"
    owner: dockeruser
    group: dockeruser
    mode: "0644"

- name: Generate docker-compose.yaml from template
  template:
    src: "templates/docker-compose.yaml.j2"
    dest: "{{ global_defaults.app_base_path }}/docker-compose.yaml"
    owner: dockeruser
    group: dockeruser
    mode: "0644"
#    force: yes # Force changes in the template to the docker-compose.yaml

- name: Eliminar contenidors orfes
  command: docker-compose --env-file {{ global_defaults.app_base_path }}/.env -f {{ global_defaults.app_base_path }}/docker-compose.yaml down --remove-orphans
  args:
    chdir: "{{ global_defaults.app_base_path }}"

- name: Deploy Docker containers
  command: docker-compose --env-file {{ global_defaults.app_base_path }}/.env -f {{ global_defaults.app_base_path }}/docker-compose.yaml up -d --force-recreate
  args:
    chdir: "{{ global_defaults.app_base_path }}"
  register: docker_up
  failed_when: docker_up.rc != 0 and "'ERROR'" in docker_up.stderr
