---
deployment_env: prod

# Copy backend files from Anisble to the server
backend_copy_build: false

# Copy angular-ssr files from Anisble to the server
angular_ssr_copy_build: false

# Expose backend port at host
expose_backend_port: false

# Expose backend to the SWAG-internal proxy
deploy_backend: false

# Base domain URLs
swag_external_url: "airconcheck.com"
swag_internal_url: "airconcheck.com"

# Backend (not exposed in prod)
backend_api_host: "http://backend:3000"

# Homepage
homepage_allowed_hosts: "homepage.airconcheck.com"

# Internal SWAG exposed services
swag_internal_services:
  - name: portainer
    port: 9000

# CoreDNS enabled por defecto en prod
# Modo: wildcard synth para *.airconcheck.com hacia Tailscale y forward del resto (apex via Internet)
coredns_enabled: true
coredns_zones:
  - zone: airconcheck.com
    wildcard_to: TAILSCALE_SELF
