- name: Crear .env per al backend (Express)
  template:
    src: backend.env.j2
    dest: "{{ global_defaults.app_base_path }}/backend/.env"
    mode: "0644"

- name: Assegurar que el directori del backend existeix
  file:
    path: "{{ global_defaults.app_base_path }}/backend"
    state: directory
    mode: '0755'

# Si vols copiar el codi buildat des d'un altre lloc:
- name: Copiar build del backend (si no es fa build in-place)
  copy:
    src: "{{ playbook_dir }}/../backend/"
    dest: "{{ global_defaults.app_base_path }}/backend/"
    mode: "0755"
