- name: Copy Express.js backend files
  copy:
    src: backend/
    dest: "{{ global_defaults.app_base_path }}/backend/"
    owner: dockeruser
    group: dockeruser
    mode: "0755"

- name: Copy express Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ global_defaults.app_base_path }}/docker/express/Dockerfile"
    owner: dockeruser
    group: dockeruser
    mode: "0644"
