- name: Crear el directori del backend si no existeix
  file:
    path: "{{ global_defaults.app_base_path }}/backend"
    state: directory
    mode: '0775'

- name: Crear .env per al backend (Express)
  template:
    src: backend.env.j2
    dest: "{{ global_defaults.app_base_path }}/backend/.env"
    mode: "0644"

- name: Copiar build del backend (si no es fa build in-place)
  copy:
    src: "/home/jose/backend/"
    dest: "{{ global_defaults.app_base_path }}/backend/"
    mode: "0755"
  when: backend_copy_build is defined and backend_copy_build

- name: Add "jose" as owner of backend/
  file:
    path: "{{ global_defaults.backend_build_context | default('/opt/airconcheck/backend') }}"
    owner: jose
    group: jose
    recurse: true
  when: false  # disabled: ownership managed centrally by docker role
