---
- name: Config the server
  hosts: all
  become: true
  pre_tasks:
    - name: Load global variables into global_defaults
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/all.yml"
        name: global_defaults
    - name: Load sensitive secrets
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/secrets.yml"
  roles:
    - ansible_user
    - express
    - docker
    - angular
    - mongodb_replica_set
    - mongo_express
#    - pmm
#    - percona_backup_for_mongodb
