---
- name: Config the server
  hosts: all
  become: true
  pre_tasks:
    - name: Load global variables into global_defaults
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/all.yml"
        name: global_defaults
    - name: Load sensitive secrets
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/secrets.yml"
    - name: Set mongo_app_url based on environment
      set_fact:
        mongo_app_url: "{{ mongo_app_url_dev if deployment_env == 'dev' else mongo_app_url }}"
    - name: Adjust docker_networks if in dev environment
      set_fact:
        docker_networks: "{{ adjusted_docker_networks | from_yaml }}"
      vars:
        adjusted_docker_networks: >-
          {% set result = [] %}
          {% for net in docker_networks %}
            {% set net = net.copy() %}
            {% if deployment_env == 'dev' and net.name == 'internal_db' %}
              {% set _ = net.update({'internal': false}) %}
            {% endif %}
            {% set _ = result.append(net) %}
          {% endfor %}
          {{ result }}
    - name: Build MongoDB replica URI
      set_fact:
        global_defaults: "{{ global_defaults | combine({
          'mongo_rs_uri':
            (
              'mongodb://%s:%s@mongo1:27017,mongo2:27017,mongo3:27017/'
              '?replicaSet=%s&authSource=admin'
            ) | format(
              mongo_root_user,
              mongo_root_password | urlencode,
              global_defaults.mongo_replicaset_name
            )
        }) }}"


  roles:
    - ansible_user
    - express
    - docker
    - angular
    - mongo_jumpbox
    - mongodb_replica_set
    - mongo_express
#    - pmm
#    - percona_backup_for_mongodb

  post_tasks:
    - name: Reconfigure replica set with public hostnames (only in dev)
      when: deployment_env == 'dev'
      block:
        - name: Wait for mongo-jumpbox container to be ready
          shell: docker exec mongo-jumpbox ls /
          register: jumpbox_ready
          retries: 5
          delay: 5
          until: jumpbox_ready.rc == 0

        - name: Reconfigure MongoDB replica set to use public hostnames
          shell: >-
            docker exec mongo-jumpbox mongosh
            "mongodb://{{ mongo_root_user }}:{{ mongo_root_password | urlencode }}@mongo1:27017/?replicaSet={{ global_defaults.mongo_replicaset_name }}&authSource=admin"
            --quiet --eval '
              cfg = rs.conf();
              cfg.members[0].host = "dev.airconcheck.com:27017";
              cfg.members[1].host = "dev.airconcheck.com:27018";
              cfg.members[2].host = "dev.airconcheck.com:27019";
              rs.reconfig(cfg, {force: true});
            '