---
- name: Config the server
  hosts: all
  become: true
  pre_tasks:
    - name: Load global variables into global_defaults
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/all.yml"
        name: global_defaults
    - name: Load sensitive secrets
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/secrets.yml"
    - name: Set mongo_app_url based on environment
      set_fact:
        mongo_app_url: "{{ mongo_app_url_dev if deployment_env == 'dev' else mongo_app_url }}"
    - name: Adjust docker_networks if in dev environment
      set_fact:
        docker_networks: "{{ adjusted_docker_networks | from_yaml }}"
      vars:
        adjusted_docker_networks: >-
          {% set result = [] %}
          {% for net in docker_networks %}
            {% set net = net.copy() %}
            {% if deployment_env == 'dev' and net.name == 'internal_db' %}
              {% set _ = net.update({'internal': false}) %}
            {% endif %}
            {% set _ = result.append(net) %}
          {% endfor %}
          {{ result }}
    - name: Build MongoDB replica URI
      set_fact:
        global_defaults: "{{ global_defaults | combine({
          'mongo_rs_uri':
            (
              'mongodb://%s:%s@mongo1:27017,mongo2:27017,mongo3:27017/'
              '?replicaSet=%s&authSource=admin'
            ) | format(
              mongo_root_user,
              mongo_root_password | urlencode,
              global_defaults.mongo_replicaset_name
            )
        }) }}"


  roles:
    - ansible_user
    - express
    - docker
    - angular
    - mongo_jumpbox
    - mongodb_replica_set
    - mongo_express
#    - pmm
#    - percona_backup_for_mongodb
