---
- name: Config the server
  hosts: all
  become: true
  pre_tasks:
    - name: Load global variables into global_defaults
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/all.yml"
        name: global_defaults
    - name: Load sensitive secrets
      include_vars:
        file: "{{ playbook_dir }}/../group_vars/secrets.yml"
    - name: Build MongoDB replica URI
      set_fact:
        global_defaults: "{{ global_defaults | combine({
          'mongo_rs_uri':
            (
              'mongodb://%s:%s@mongo1:27017,mongo2:27017,mongo3:27017/'
              '?replicaSet=%s&authSource=admin'
            ) | format(
              mongo_root_user,
              mongo_root_password | urlencode,
              global_defaults.mongo_replicaset_name
            )
        }) }}"


  roles:
    - ansible_user
    - express
    - docker
    - angular
    - mongodb_replica_set
    - mongo_express
    - mongo_jumpbox
#    - pmm
#    - percona_backup_for_mongodb
