---
- name: Config the server
  hosts: all
  become: true
  vars_files:
    - ../group_vars/secrets.yml  # Ruta relativa desde playbooks/
    - "{{ playbook_dir }}/../group_vars/all.yml"
  roles:
    - ansible_user
    - docker
    - angular
    - expres
    - mongodb
